version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sporkmonger
  labels:
  - dependencies
  ignore:
  - dependency-name: github.com/uber/jaeger-client-go
    versions:
    - 2.25.0+incompatible
    - 2.26.0+incompatible
  - dependency-name: github.com/rs/zerolog
    versions:
    - 1.20.0
